import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={
          "pattern-bg flex min-h-screen items-center justify-center p-md font-body-md text-on-surface"
        }
      >
        {children}
      </body>
    </html>
  );
}
